# Generated by Django 2.2.2 on 2020-07-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livepocket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=100)),
                ('eventDate', models.DateTimeField()),
                ('description', models.CharField(max_length=1000)),
                ('ticketType', models.CharField(max_length=50)),
                ('ticketQuantity', models.IntegerField()),
                ('ticketPrice', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='hedgehog',
            name='pile_color',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='HedgeHog',
        ),
        migrations.DeleteModel(
            name='PileColor',
        ),
    ]
