# Generated by Django 2.2.2 on 2020-07-18 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livepocket', '0002_auto_20200718_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='eventDate',
            new_name='event_date',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='eventName',
            new_name='event_name',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='ticketPrice',
            new_name='ticket_price',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='ticketQuantity',
            new_name='ticket_quantity',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='ticketType',
            new_name='ticket_type',
        ),
    ]
